# docker-compose.yml
version: "3.8"

services:
    db:
        image: postgres:15
        container_name: puppet_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: puppet
            POSTGRES_USER: puppet_user
            POSTGRES_PASSWORD: puppet_pass
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
